### ISSUE TITLE
Lookup table sorting improvements & integrity checker

### ISSUE THREAD

**Issue by exelia-antonov** [dialogic-godot/dialogic#1214]
Should be in place by 2.0 full release, but doesn't need to be focused on for alpha and beta steps:

So I'm not enitrely happy with how the generation for the lookup table for partial paths works, its ok but it could be more robust. I was trying to do a multi-step sorting all in one so it would be in full alphabetical order also by path, but its gonna need multiple stages of generation because one single one doesn't seem to work.  The most important thing is it needs to be consistently predictable regardless, so like if you're putting in to load either a timeline or a character just by just the partial name instead of the full name, it should always go by the first one in the list so should always have expected behavior. The closer to root level they are in the folder is the first in the order, which is how it works but not entirely alphabetical. It was also generating more of a unique folder then actually necessary, in a few cases in my existing project setups.

But I was thinking this morning of adding like an integrity checker to the settings sometime before 2.0 full release, so it will actually show you how Dialogic generates the lookup tables, and check all the timelines and show which characters and timelines is point at so at a glance you can make sure it's the right one and correct it if it generated wrong. Because, for example, if you have a timeline with `[jump timeline="Shop/Shopkeeper"]`, and at the time you made it the two files were `res://towns/Town B/Shop/Shopkeeper.dtl` and `res://towns/Town B/Junkyard/Shopkeeper.dtl`, when the timeline was saved those were the only two there and so that path was correct, but then if you later added `res://towns/Town A/Junkyard/Shopkeeper.dtl` and `res://towns/Town A/Shop/Shopkeeper.dtl`, the lookup table would be changed to include the 'Town A' or 'Town B' as part of it. And since then 'Shop/Shopkeeper' by itself is no longer in the lookup table, it would fallback to going through each of them by full path, and encounter Town A instead when you meant it to point at Town B. 

So the integrity checker would be a like thing you run every so often or at your final pass before project export, to make sure everything's pointing at the right character and timeline. It would show the actual full lookup table at the time, with the full file path and what short name that path is using, then load up and check each timeline and show you them one at a time, letting you view everything that uses the lookup table, to just quickly look and see what everything is pointing at, highlighting any entry that isn't in the lookup table (if it's not using the full path, because you can always enter those too in text timelines) so you know if there's any that you need to go make changes to.

**Comment by thebardsrc** [comment]
additionally, if possible, see about reintegrating the events back into the timeline loader, to make it easier to use Godot's built-in dependency checker for links. 

a quick preliminary check with the event cache being built on each `_load()` event doesn't seem *too* bad in performance, although between Godot alpha inspector bugs in general, and all the things disconnected due to the current changes, that doesn't necessarily mean it won't increase a whole lot more than expected: 
![image](https://user-images.githubusercontent.com/2214793/189240883-dcf5da92-17a6-490d-82e0-612e548168d4.png)

that is, of course, made much more complicated due to the Editor. changes are easy enough to be whatever for runtime. 

it may not be possible to do this, though, beacuse it may not be easy to resolve the lookup tables. that would probably be doable in DialogicUtil by generating a table for the loader identical to how DGH generates it, and _is_ only needed for Editor, but it also might slow down Editor a lot which we don't want either.  and the integrity checker will still be needed, though, because externally-created timelines still exist and you still need to be able to make sure the loader converted all the character and timeline references into the right resource properly
