### ISSUE TITLE
BBCode with Text Letter Speed

### ISSUE THREAD

**Issue by KBrooke19** [dialogic-godot/dialogic#1910]
I'm having an issue with implementing BBCode into my dialogue.  It seems that whenever I add any form of [] tags into the text that aren't exclusive _to_ Dialogic, there's a kind of lag with the reveal speed.  While the tags don't necessarily display, the text crawl still acts like they have been, with new sentences beginning with several characters being revealed on input before the individual reveal begins, and auto-pauses running on the wrong characters accordingly with the delay.

**Steps to reproduce the behavior:**
1. Create a new timeline and text box.
2. Implement autopauses from Settings > Text > AutoPause
3. Type a sentence using BBCode tags and characters used in autopause.
4. Click "Play Timeline"

I would simply like to be able to use BBCode in my text without any timing delays.

**System:**
 - OS: Linux, 6.1.62-1-MANJARO (64-bit)
 - Godot Version: v 4.1.3.stable.official
 - Dialogic Version: 2.0-Alpha-11 (Godot 4.1+)

**Comment by Jowan-Spooner** [comment]
Hey @KBrooke19, sorry for the long delay.
I'm currently trying to recreate this problem, but it seems to work fine for me.
Can you give us a specific text that had this problem?

**Comment by coppolaemilio** [comment]
@Jowan-Spooner I was able to reproduce. It happens if you change the default text speed from 0.01 to something like 0.03 in settings>Text>Default letter speed, otherwise it is not noticeable. 
There wasn't any editing in the recording, it is this abrupt when skipping to the next line:
![speedbug](https://github.com/dialogic-godot/dialogic/assets/2206700/1605587e-cacd-4f68-b0c1-94bb7ed2eb30)

It seems like the text "keeps revealing itself" but you make it visible only when you press the input key.
