### ISSUE TITLE
Make possible to use array vars in dialogs

### ISSUE THREAD

**Issue by APAmk2** [dialogic-godot/dialogic#1928]
**Is your feature request related to a problem? Please describe.**
Yes, when trying to use one of the vars from array - Dialogic not allows me to do this and ignore it, when using non-array variables - everything works fine, that's looks like base thing that need to be in plugin since beginning, but it isn't and that's annoying.

**Describe the solution you'd like**
Make possible to use arrays in dialogs.

**Comment by Jowan-Spooner** [comment]
Please provide more info: 
- which dialogic version do you use?
- what did you try already to make it work?
- what is your concrete use case?

Arrays and Dictionaries are not possible types for dialogic 2 variables (currently strings only). 
This is because you can already access Arrays and Dictionaries from autoloads fine which solves most use cases.
```
# Example text event that picks a random word from an array
Random word: {Autoload.array[randi()%Autoload.array.size]}
```

Allowing dialogic variables to be arrays and dictionaries would be a huge work, less so from an implementation perspective as from a UI perspective. 
The value picker of the Set Variable event is already (nearly) the most complex input field we have. Adding support for dictionaries and arrays (which are really complex to handle in a UI) would be a lot of work, so we would needd to make sure it's worth it.

Feel free to provide more context for the problem you are facing.

**Comment by APAmk2** [comment]
Sorry for wait, forgot about this.
The problem is in setting/getting values from string arrays in autoloads, for example
`set {GlobalVars.anna[0]} = "srushalcohol"
...
if {GlobalVars.anna[0]} == "srushalcohol":`
Doesn't works, but if i separate this array to single string vars - that works.
