### ISSUE TITLE
dialogic_default_action is ignored if triggered by parse_input_event()

### ISSUE THREAD

**Issue by MindFlayeR57** [dialogic-godot/dialogic#1976]
## The problem

**Describe the bug**
when using parse_input_event() to trigger dialogic_default_action the action gets triggered but Dialogic ignores it

**To Reproduce**
1. write code that uses parse_input_event() to trigger dialogic_default_action.
2. nothing happens.

**Expected behavior**
the textbox advances to the next piece of dialog.

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.2.1
 - Dialogic Version: 2.0 alpha 12

**Comment by Jowan-Spooner** [comment]
@MindFlayeR57 Thanks for the report. 

Dialogic input handeling is a bit complex because mouse inputs are collected by a control node and other inputs are only checked for in _unhandled_input(). I'm not sure if this is something we are doing wrong or to be expected in this situation.

However the correct way to make dialogic react to "fake" input is to call `Dialogic.Input.handle_input()`.

**Comment by MindFlayeR57** [comment]
> However the correct way to make dialogic react to "fake" input is to call `Dialogic.Input.handle_input()`.

This is going to complicate things with how I've implemented Steam Input but thank you nonetheless!
