### ISSUE TITLE
Setting variables in dictionaries or arrays not working.

### ISSUE THREAD

**Issue by Pynthare** [dialogic-godot/dialogic#2195]
## The problem

**Describe the bug**
I am using a singleton dictionary to store the information for each quest that is currently in my game. I can fetch information from this dictionary without problem e.g: "if {Quest.quests["shipHullRepairPart1"].status} == 0:" and it works flawlessly.

However, when tring to SET a variable e.g: "set {Quest.quests["shipHullRepairPart1"].status} = 1", dialogic just trows a tantrum in the output log:
Dialogic: Expression failed to parse: Expected expression.
[Dialogic] Failed parsing variable/expression ''.

This also appears when tring to use other parts, like using a variable to minus itself using another variable:
![image](https://github.com/dialogic-godot/dialogic/assets/149574826/9d1c2949-091c-4713-b211-e43a1f419f5e)
If I look in the timeline files this is not even saved correcly:
"set {{Itemresource.inventoryResources[0].amountOwned}} -= {}"

**To Reproduce**
Try setting any variable in a dictionary or .

**Expected behavior**
I would expect dialogic to set the variables and save the entered variables.

**System (please complete the following information):**
 - OS: Windows 11
 - Godot Version: 4.2.1
 - Dialogic Version: 2.0 alpha 13

Am I missing something supidly obvious?

**Comment by CakeVR** [comment]
Hello, please try again with the latest commit on the `main` branch.

**Comment by Pynthare** [comment]
Hi, thank you for your response. I tried updating to the latest commit, and sadly no change. I did however try to force the entry of the variable by adding it into the timeline-file manualy with code. This gave the error "Quest.quests["shipHullRepairPart1"].objectiveAmount" which leads me to belive dialogic does not recognize that this is acctualy a autoloaded gd-file for some reason.

**Comment by Jowan-Spooner** [comment]
Hey @Pynthare The access to arrays and dictionaries is for now limited to this syntax `array["my_entry"]` while `array.my_entry` is not supported. This is simply because noone had the time to implment that, as it makes the code much more complex (because it's harder to differentiate from member access of an object). 

So you should be able to do what you want with: `{Itemresource.inventoryResource[0]["amountOwned"]}`

I have created a new separate feature request (#2197) for that syntax so we can track the missing functionality there.
