### ISSUE TITLE
Allow the use of variables when choosing portrait

### ISSUE THREAD

**Issue by szyhar** [dialogic-godot/dialogic#2199]
I wanted to have a feature where the player is able to choose one of the character's portraits. The simplest way to do this would be to set the portrait using a variable, but this doesn't seem to be possible now. 

For now, I can get around this issue by setting a series of conditionals when the character first appears in a given timeline, but that is quite an inelegant solution.

Thanks a lot for your work.

**Comment by Jowan-Spooner** [comment]
I've made a PR that should allow this. I'm pretty sure we had something similar in 1.x, and I think this is a pretty cool feature that makes the portrait system a bunch more flexible.

**Comment by szyhar** [comment]
Thanks a ton for this and all the work you guys do. I'm new here, is it possible for me to get notified when this gets added to the main branch?

**Comment by Jowan-Spooner** [comment]
When this get's merged this issue will be closed, so I think you will get a notification anyways. I think you can also subscribe to the PR if needed. 
To be quite honest, it's most likely I just merge this today or tomorrow. This project unfortunately isn't big enough for a lot of reviews, so while I usually keep things open for some time in case someone wants to comment/try, I'll usually merge small things after some time, without second review, because we would not get anywhere otherwise.
