### ISSUE TITLE
History enabled by default, but shown as disabled in the settings

### ISSUE THREAD

**Issue by coppolaemilio** [dialogic-godot/dialogic#2228]
Dialogic: latest from `main`
Godot version: 4.3.dev6

I created a test timeline, and noticed that now, on a brand new project, you see the history button at the top. 
<img width="575" alt="image" src="https://github.com/dialogic-godot/dialogic/assets/2206700/36b187b0-e67d-4cf5-b157-06fdf168a14b">
But the project settings have this unchecked:
<img width="1053" alt="image" src="https://github.com/dialogic-godot/dialogic/assets/2206700/caefafc5-2a2d-47ab-ad1f-6b7419f54a2f">

I think the history button should only show if you actively want it by enabling in the settings. So I'd say the settings are correct here and the default template is not.

**Comment by coppolaemilio** [comment]
Additionally, if you toggle the first checkbox, it will be correct and hide the history button

**Comment by Jowan-Spooner** [comment]
Then this is probably a problem with default values. 
Usually we assume default values for dialogic settings in multiple places and those assumptions can get out of sync. So I'd assume the game assumes it's on by default, while the settings page considers it off by default. This happens when no actual value has been stored for the setting.

**Comment by coppolaemilio** [comment]
Makes sense, so I guess the fix would be to disable the history by default on the default theme 👍
