### ISSUE TITLE
Dialogic Issue: Invalid call. Nonexistent function 'get_local_portrait_' in base 'Control (DialogicNode_PortraidContainer)'.

### ISSUE THREAD

**Issue by Blackdarkova** [dialogic-godot/dialogic#2364]
Hi there. I just got this error and I don't understand what I have to do to fix it. It's worth mentioning that I wasn't adding a custom portrait, I created a character as I normally do and added a simple png image to it. It's strange because previously it allowed me to 
create portraits normally, so I don't know what happened.

Issue: Dialogic Issue: Invalid call. Nonexistent function 'get_local_portrait_' in base 'Control (DialogicNode_PortraidContainer)'.

Godot Version is the: v4.2.2.stable.official[15073afe3]
Dialogic 2 Version

I hope someone can help me, I don't understand how to solve it.

![NewCanvas3](https://github.com/user-attachments/assets/eb782035-0768-4d1c-b2e8-fb10dee6c00b)

**Comment by neilowhite** [comment]
Hi, I'm not at all sure, but there's something you can try: The code looks like there *might* be a bug in the code. It's going to mean changing the Dialogic code in order to test this, but it's a tiny change, and if it doesn't work it's very easy to put the code back. Even so, proceed at own risk!

In this line:

var transform: Rect2 = character_node.get_parent().get_local_portrait(

Try removing .get_parent()

The reason for this is that at the top of the visible script, there is a line -

var character_node: Node = portrait_node.get_parent()

It **may** be that this has been overlooked when the transform variable is set. I don't know why this would work any differently to how you have set up other characters, and in any case it's not something that I've tested, so please be aware that this is just a suggestion based on what I can see!

So, change the line to:

var transform: Rect2 = character_node.get_local_portrait(

Save, and run your game. If it's still broken, or breaks everything else, then simply restore that line to how it was and, well, you're back where you were. If it *does* fix it, wonderful, and maybe try to report to the devs.

Good luck!

**Comment by Blackdarkova** [comment]
Thank you, Thanks for the tip, I restored the original Dialogic files and it worked, I don't understand what went wrong, I don't remember touching a single line of code. It's a bit frustrating when these errors occur, but I'm having a lot of fun using the plugin.

**Comment by Jowan-Spooner** [comment]
Hi @Blackdarkova,
It's unclear to me what has happened here tbh. The method called on that line is obviously missing something (the line should be `var transform: Rect2 = character_node.get_parent().get_local_portrait_transform(`, and I'm pretty sure this must have happened on your end. Most likely you've somehow accidentally removed it? Idk. As this has gotten resolved I will close this unless this happens to someone else in the future. 

Speaking of in the future, if you make issues in the future, we'd appreciated something more precise then Dialogic 2 (there are many versions and dialogic 1 is on a different repo anyways), thanks :)
